version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: springdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: /bin/sh -c "ollama run qwen3:0.6b || true && ollama serve"


  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on:
      - postgres
      - ollama
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runnable:
    build:
      context: ./runnable
      dockerfile: Dockerfile
    image: coding-agent:latest
    ports:
      - "5900:5900"       # VNC server
      - "6080:6080"       # noVNC web access
    depends_on:
      - ollama
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./output:/output

volumes:
  pgdata:
  ollama_data:

